### ISSUE TITLE
fail in version 2023.3

### ISSUE THREAD

**Issue by vMeph** [netsoft-ruidias/ha-custom-component-sodexo#3]
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for sodexo using this method at custom_components/sodexo/__init__.py, line 27: hass.config_entries.async_setup_platforms(entry, PLATFORMS

**Comment by netsoft-ruidias** [comment]
Fixed in version v1.2.0
